#!/bin/bash

# ssync syncfile/ remotefile/ root@remote root@remote2

syncroot=`eval "echo $1"`
remoteroot=$2
shift 2
remotes="$@"


[ -z "$syncroot" ] && syncroot="."

if [ "$syncroot" == "." ]
then
    syncroot=`pwd`
    echo $syncroot
fi

modified=`stat -c %Y ${syncroot}`

function copyfolder() {
    echo $syncroot
    echo $remoteroot

    for remote in $remotes
    do
        echo "syncing to $remote:${remoteroot}"
        scp $syncroot "${remote}:${remoteroot}"

    done

    echo "finished syncing"    
}

function checkChanged() {
    modified_now=`stat -c %Y $syncroot`
    if [ "$modified" -eq "$modified_now" ]
    then
        return 0
    fi
    copyfolder
    modified=$modified_now
}

while true
do
    checkChanged
    sleep 3
done
