#!/bin/bash

# usage
# ssync syncfile/ remotefile/ root@remote root@remote2

syncroot=`eval "echo $1"`
remoteroot=$2
shift 2
remotes="$@"

exit_script() {
    echo "Exiting ssync"
    trap - SIGINT SIGTERM
    kill -- -$$
}

trap exit_script SIGINT SIGINT

if [ ! -e "$syncroot" ]
then
    echo "error: local file ¬∃"
    echo "exiting"
    exit 1
fi

modified=`stat -c %Y $(find $syncroot -type f)`

function init() {
    echo "copying ssh public key to remote"
    for remote in $remotes
    do
        ssh-copy-id $remote
        [ $? -ne 0 ] && echo "failed copying ssh key to $remote"
    done
    echo "finished init process"
}

function copyfolder() {
    echo "begin sync cycle"
    for remote in $remotes
    do
        echo "syncing to $remote:$remoteroot"
        echo "$syncroot"
        scp -r "$syncroot" "$remote:$remoteroot"
        [ $? -ne 0 ] && echo "failed sycning to $remote:$remoteroot"
    done

    echo "finished syncing"    
}

function checkChanged() {
    modified_now=`stat -c %Y $(find $syncroot -type f)`
    if [ "$modified" == "$modified_now" ]
    then
        return 0
    fi
    copyfolder
    modified=$modified_now
}

init

while true
do
    checkChanged
    sleep 3
done
